### ISSUE TITLE
Link incorrectly garbage-colleged

### ISSUE THREAD

**Issue by Otlichno** [Segs/Segs#441] opened 2018-06-07 15:30 UTC
When setting up my public server I ran into this issue because the firewall ports for the map server were not opened correctly (Documentation bug). Nemerle stated the below:
This looks like the client communication failed at some point , and then link is incorrectly 'garbage-collected/reaped' could be caused by the mapserver not receiving any data thus gameserver closing the link, and then client sending data on the closed-link's port

**Comment by Otlichno** [comment] 2018-06-07 15:58
Debug   : Login successful
Debug   : Client requesting server list...
(6816|140737113765632) Client selected server 1!
Warning : Create_cookie still needs a good algorithm. 0x54d406f9
authserver: /home/crounce/project/Segs/Projects/CoX/Common/Servers/ClientManager.h:203: void ClientSessionStore<SESSION_CLASS>::remove_from_active_sessions(SESSION_CLASS*) [with SESSION_CLASS = GameSession]: Assertion `false' failed.
authserver: /home/crounce/project/Segs/Projects/CoX/Common/Servers/ClientManager.h:113: SESSION_CLASS& ClientSessionStore<SESSION_CLASS>::session_from_token(uint64_t) [with SESSION_CLASS = AuthSession; uint64_t = long unsigned int]: Assertion `iter != m_token_to_session.end()' failed.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffd9da0700 (LWP 6825)]
0x00007ffff6520277 in raise () from /lib64/libc.so.6

**Comment by broxen** [comment] 2018-08-02 09:07
@cameron-justice, can you confirm that this is on v0.5.0 release?

**Comment by broxen** [comment] 2018-09-09 00:12
I'm going to close this as I've been unable to reproduce and the submitter has not responded in over 30 days.

**Closed by broxen** 2018-09-09 00:12 UTC
Labels: bug, v0.5.0
