### ISSUE TITLE
Bug Reporting In Game

### ISSUE THREAD

**Issue by Taygai** [Segs/Segs#287] opened 2018-04-06 00:58 UTC
### Expected behavior
When reporting a bug it should not crash the game, rather give a confirmation of it being sent.

### Actual behavior/symptoms
After submitting the summary and full description of the bug, then clicking send petition it crashes the authserver saying the client has encountered an issue. It seems to be related to event type 13

### Steps to reproduce behavior/symptoms
Click Menu on the top right, then support, then attempt to file a bug report, 

### SEGS version
v0.4.2

### Operating system
Windows 10 64 bit

**Comment by Taygai** [comment] 2018-04-06 01:00
Sorry about  the blank notification, should be working now

**Comment by broxen** [comment] 2018-05-01 03:50
Closing this as duplicate of #35

**Closed by broxen** 2018-05-01 03:50 UTC
Labels: duplicate, enhancement, wishlist
