### ISSUE TITLE
Server Crashes/Freezes in Public Test Servers

### ISSUE THREAD

**Issue by EmileFrost** [Segs/Segs#829] opened 2019-04-03 00:19 UTC
Both Red and Blue servers often crash shortly after logging in. This can be anywhere from 10 seconds to 5 minutes after logging in. When the freeze happens, chat stops working and slash commands do not work - movement is still possible. 

No notification that the server has gone down or DC'd immediately. Sometimes there is a "disconnected from mapserver" status message, other times not. 

Unable to log off or quit game while freeze is occuring.

The crash/freeze has occured:

- Being the only one on the map
- With others on the map
- In different zones
- In teams
- Solo
- While flying
- While standing
- Sometimes after interacting with LuaBot (not always)
- Sometimes after inviting another player to a team (not always)
- When a player logs off (causes a mapserver disconnection)

**Comment by broxen** [comment] 2019-04-04 05:27
Blue crashed tonight at 05:05:30 UTC with the following error message after I tried to zone to Outbreak with the mapmenu
```cpp
Apr 04 05:05:30 blue segs_server.sh[125000]: segs_server: /opt/segs/Segs/Projects/CoX/Common/Servers/ClientManager.h:126: SESSION_CLASS& ClientSessionStore<SESSION_CLASS>::session_from_event(SEGSEvents::Event*) [with SESSION_CLASS = MapClientSession]: Assertion `iter!=m_token_to_session.end()' failed.
```
Console output (reverse order):
```
Apr 04 05:05:25 blue segs_server.sh[125000]: [05:05:25] [log.mapevents]Warning : "SetDestination request: 36 <192.0, 0.0, -117.0>"
Apr 04 05:05:25 blue segs_server.sh[125000]: [05:05:25] [log.slashcommand]Debug   : "Sending SendWaypoint: 36 <192.0, 0.0, -117.0>"
Apr 04 05:05:25 blue segs_server.sh[125000]: [05:05:25] [log.mapevents]Warning : "SetDestination request: 37 <192.0, 0.0, -117.0>"
Apr 04 05:05:25 blue segs_server.sh[125000]: [05:05:25] [log.slashcommand]Debug   : "Sending SendWaypoint: 37 <192.0, 0.0, -117.0>"
Apr 04 05:05:25 blue segs_server.sh[125000]: [05:05:25] [log.mapevents]Warning : "SetDestination request: 38 <192.0, 0.0, -117.0>"
Apr 04 05:05:25 blue segs_server.sh[125000]: [05:05:25] [log.slashcommand]Debug   : "Sending SendWaypoint: 38 <192.0, 0.0, -117.0>"
Apr 04 05:05:27 blue segs_server.sh[125000]: [05:05:27] Debug   : Unresponsive link
Apr 04 05:05:29 blue segs_server.sh[125000]: [05:05:29] [log.mapevents]Debug   : Dialog success true
Apr 04 05:05:29 blue segs_server.sh[125000]: [05:05:29] [log.mapevents]Debug   : Entity:  973 has received DialogButton 2 true
Apr 04 05:05:29 blue segs_server.sh[125000]: [05:05:29] [log.slashcommand]Debug   : Sending ContactDialogClose
Apr 04 05:05:29 blue segs_server.sh[125000]: [05:05:29] [log.slashcommand]Debug   : Showing MapXferList: "<linkhoverbg #118866aa><link white> // and so on...
Apr 04 05:05:30 blue segs_server.sh[125000]: segs_server: 
/opt/segs/Segs/Projects/CoX/Common/Servers/ClientManager.h:126: SESSION_CLASS& ClientSessionStore<SESSION_CLASS>::session_from_event(SEGSEvents::Event*) [with SESSION_CLASS = MapClientSession]: Assertion `iter!=m_token_to_session.end()' failed.
Apr 04 05:05:30 blue systemd[1]: segs.service: main process exited, code=exited, status=134/n/a
Apr 04 05:05:30 blue systemd[1]: Unit segs.service entered failed state.
Apr 04 05:05:30 blue systemd[1]: segs.service failed.
Apr 04 05:05:31 blue systemd[1]: segs.service holdoff time over, scheduling restart.
Apr 04 05:05:31 blue systemd[1]: Stopped SEGS community test server.
Apr 04 05:05:31 blue systemd[1]: Started SEGS community test server.
// and then the server restarts
```

**Comment by nemerle** [comment] 2019-04-04 06:59
The failure of `iter!=m_token_to_session.end()` assertion means that the server decided that a link is dead and removed its session, or never knew about it ( less likely ), but received a new packet for that link.
The fact that this keeps happening suggests that we're over-eager when marking/removing sessions.

**Comment by broxen** [comment] 2019-04-05 05:13
## Summary
Blue froze at roughly 5:00am UTC Apr 5 but did not actually crash

### Steps prior to server freeze
- Started killing some baddies in Outbreak. 
- Then went afk while hovering.
- Server console showed Sending new PowerStance on loop
- Came back, tried to disable Hover, or do anything else, but couldn't #835 
- Received AutoAFK message (presumably late, because I'd been gone awhile) #834 
- Couldn't close client, chat, or really do anything
- Force stop client (xkill)
- Server still reporting Sending new PowerStance on loop
- Rebooted client and attempted login
- Received Server is unavailable message
- Server output finally shows that it froze (no new output, hasn't crashes though)

**Comment by broxen** [comment] 2019-04-09 04:01
Mobby got this again the evening of Apr 8 when logging into this local server after building from a fresh install.

Happened immediately upon login
```
[22:51:14] Spun up MapInstance 1 for MapServer 1
[22:51:14] Loading map instance data...
[22:51:15] Critical: Can't find .geo file "object_library/Omni/EncounterSpawns/City_00_01/City_00_01.geo"
[22:51:15] Critical: Can't find .geo file "object_library/Omni/EncounterSpawns/City_01_03/City_01_03.geo"
[22:51:15] Debug   : Loading original scene graph ... done in 1.263 s
[22:51:16] Debug   : Spawning npcs ... done in 0.781 s
[22:51:16] Loading custom scripts
[22:51:16] GameDbSyncService loaded/configured
[22:51:16] Warning : Create_cookie still needs a good algorithm. 0xa00ddfd
[22:51:16] Loading Starting Character Settings...
[22:51:16] Debug   : Scene Request: unkn1: 1, undos_PP: 0, current_map_flags: 1
[22:51:44] Debug   : Unresponsive link
Assertion failed: (iter!=m_token_to_session.end()), function session_from_event, file /Users/kb2mob/Segs/Projects/CoX/Common/Servers/ClientManager.h, line 126.
```

**Comment by broxen** [comment] 2019-04-10 05:45
Apr 9 on red @ldilley and I discovered the following happening to myself and @EmileFrost while trying to log in and select the server:
```
[05:35:15] Debug   : User segsadmin trying to login from x.x.x.x
[05:35:18] Debug   : AuthHandler Reaping stale link 151318384
[05:35:25] Debug   : User broxen trying to login from x.x.x.x
[05:35:28] Debug   : AuthHandler Reaping stale link 249619712
[05:35:31] Debug   : User broxen trying to login from x.x.x.x
[05:35:31] Debug   : Server Account Id : 8
[05:35:31] Debug   : Login successful
[05:35:31] Debug   : Client requesting server list...
[05:35:32] Warning : Create_cookie still needs a good algorithm. 0x637fd89a
[05:35:33] Spun up MapInstance 2 for MapServer 1
// ...
[05:36:03] Warning : Unhandled reconnect packet??
[05:36:06] Debug   : AuthHandler Reaping stale link 249620736
```
So it's definitely **The Grim Reaper** :rofl:

**Comment by broxen** [comment] 2019-04-10 06:10
We have multiple different values for `link_is_stale_if_disconnected_for` in the code base:
```cpp
    const ACE_Time_Value link_is_stale_if_disconnected_for(0,4*1000*1000); // AuthHandler.cpp
    const ACE_Time_Value link_is_stale_if_disconnected_for(5,0); // GameHandler.cpp
    const ACE_Time_Value link_is_stale_if_disconnected_for(0,5*1000*1000); // MapInstance.cpp
```
I still can't replicate locally, but perhaps we test Red/Blue with AuthHandler set to `(0,5*1000*1000)`?

**Comment by nemerle** [comment] 2019-04-10 06:49
Shorter 'stale' time in auth handler is meant to reduce frustrations with 'already-logged in' messages.
as for parameter layout for ACE_Time_Value, it's `seconds, microseconds` so we could normalize that to `(5,0)`

**Comment by broxen** [comment] 2019-04-10 08:15
It seems that I can reliably reproduce the server hang locally by using `xkill` on the CoX client window, and quickly trying to log back in with the same account.

This is the only output I get from the server in that scenario.
```cpp
[01:11:53] Debug   : User segsadmin trying to login from x.x.x.x
[01:11:53] Debug   : Server Account Id : 1
[01:11:55] Debug   : AuthHandler Reaping stale link 140736817279936
(30226|140737296756864) Error sent, closing connection
(30226|140737296756864) Connection closed
[01:11:56] Debug   : User segsadmin trying to login from x.x.x.x
[01:11:56] Debug   : Server Account Id : 1
[01:11:58] Debug   : AuthHandler Reaping stale link 140736817282384
```

**Comment by broxen** [comment] 2019-04-12 07:30
Interesting crash on Blue tonight.

Idled to AFK, after being afk for awhile I recovered, but AFK would not unset (#834 which we thought was resolved), had to force quit client. Could not reconnect, as server thought account was still logged in.

Further, the server finally froze. Output below:
```
[07:11:59] [log.mapevents]Warning : Incomplete Unqueue all request. Setting Target and Assist Target to 0
[07:12:00] Warning : UnqueueAll unimplemented.
[07:12:00] [log.mapevents]Warning : Incomplete Unqueue all request. Setting Target and Assist Target to 0
(75962|140691842349248) Connection closed
(75962|140691842349248) Connection closed
[07:22:11] Debug   : User broxen trying to login from x.x.x.x
[07:22:11] Debug   : Server Account Id : 2
(75962|140691842349248) Error sent, closing connection
(75962|140691842349248) Connection closed
[07:22:15] Debug   : User broxen trying to login from x.x.x.x
[07:22:15] Debug   : Server Account Id : 2
(75962|140691842349248) Error sent, closing connection
(75962|140691842349248) Connection closed
[07:22:21] Debug   : User broxen trying to login from x.x.x.x
[07:22:21] Debug   : Server Account Id : 2
(75962|140691842349248) Error sent, closing connection
(75962|140691842349248) Connection closed
[07:23:03] Debug   : User broxen trying to login from x.x.x.x
[07:23:03] Debug   : Server Account Id : 2
```

**Comment by broxen** [comment] 2019-05-05 20:07
As of latest tests, this doesn't appear to be happening anymore. Closing for now and will reopening if further testing reveals that there is a lingering issue here.

**Closed by broxen** 2019-05-05 20:07 UTC
Labels: bug, release blocker
