### ISSUE TITLE
Client crashes after multiple login/logout events

### ISSUE THREAD

**Issue by broxen** [Segs/Segs#273] opened 2018-03-21 02:28 UTC
### Steps to reproduce
Keep server running the entire time. Log in and out of the same account multiple times. Logging in and out of different accounts will produce the same effect with less consistency.

### OS and Server Version.
Tested against current commit 20332196 on Linux only. I would love it if someone can confirm on Win or OSX.

### Notes
Initially I thought this was related to Having set titles for a character, as it happened twice right after doing so, but I can confirm that it happens without titles as well. It's possible that they are two separate issues masquerading as each other.

**Comment by ldilley** [comment] 2018-03-21 21:17
I was unable to reproduce this symptom using 2033219 under FreeBSD 11.1-RELEASE 64 bit when logging in with "joe/joe" and backing out from server select back to login screen. I attempted this 50 times in fairly rapid succession with no peculiar result. Do you have to actually connect to the game/map server and logout (waiting 10 seconds) to induce the crash?

**Comment by broxen** [comment] 2018-03-21 22:19
In my experience yes. You must actually log into the mapserver (game world)

**Comment by ldilley** [comment] 2018-03-21 23:15
I never did get the client to crash using the long logout route. I did manage to get the server to crash just moments ago doing this however. The server aborts during a call to the following method and assertion:

```
Warning : Unhandled unqueue all request: -1
Warning : Unhandled unqueue all request: -1
ACE_ASSERT: file /home/ldilley/Segs/Projects/CoX/Common/Servers/ClientManager.h,
line 96 assertion failed for 'getById(id)!=0'.Aborting...
Abort (core dumped)
```

```cpp
void ClientManager::removeById(uint64_t id)
{
    ACE_ASSERT(getById(id)!=0);
    ...
}
```

Stack trace:
```
(lldb) target create "./authserver" --core "authserver.core"
Core file '/home/ldilley/Segs/bld/out/authserver.core' (x86_64) was loaded.
(lldb) bt
* thread #1, name = 'authserver', stop reason = signal SIGABRT
  * frame #0: 0x00000008026bf84a libc.so.7`__sys_thr_kill + 10
    frame #1: 0x00000008026bf814 libc.so.7`raise + 52
    frame #2: 0x00000008026bf789 libc.so.7`abort + 73
    frame #3: 0x0000000800fb37f9 libACE.so`ACE_OS::abort(void) + 9
    frame #4: 0x0000000800f853f2 libACE.so`ACE_Log_Msg::log(char const*, ACE_Log_Priority, __va_list_tag*, ACE_Log_Category_TSS*) + 19618
    frame #5: 0x0000000800f8073c libACE.so`ACE_Log_Msg::log(ACE_Log_Priority, char const*, ...) + 348
    frame #6: 0x0000000800f256e5 libACE.so`__ace_assert(char const*, int, char const*) + 197
    frame #7: 0x000000000049b049 authserver`ClientStore<MapClient>::removeById(unsigned long) + 89
    frame #8: 0x00000000004b4d20 authserver`MapInstance::on_disconnect(DisconnectRequest*) + 208
    frame #9: 0x00000000004b417d authserver`MapInstance::dispatch(SEGSEvent*) + 1117
    frame #10: 0x0000000000598aa2 authserver`EventProcessor::svc(void) + 162
    frame #11: 0x000000080101db6d libACE.so`ACE_Task_Base::svc_run(void*) + 77
    frame #12: 0x000000080101e9a1 libACE.so`ACE_Thread_Adapter::invoke_i(void) + 273
    frame #13: 0x000000080101e851 libACE.so`ACE_Thread_Adapter::invoke(void) + 273
    frame #14: 0x0000000800f3af2e libACE.so`ace_thread_adapter + 30
    frame #15: 0x0000000800a66bc5 libthr.so.3`___lldb_unnamed_symbol1$$libthr.so.3 + 325
```

**Comment by ldilley** [comment] 2018-05-10 02:47
I concur. This likely disappeared with the implementation of the message bus and thread changes. I've assigned the invalid label and will close this out.

**Closed by ldilley** 2018-05-10 02:47 UTC
Labels: bug, invalid
